src/lib.rs

regexes with optional captures will panic if that capture is not present
in a string, i.e. r"hello( \s)?" will panic on "hello"
another way to handle this would be to return on Option<String> however
that would change the API

return empty string instead of panicing on non-existant regex captures

---

Cargo.toml
README.md
build.rs

Avoid builds failing using stable Rust by automatically detecting Rust
nightly using a build script and the rustc_version crate.

Use rustc_version to automatically detect Rust nightly

---

src/lib.rs
tests/cucumber.rs

The steps! macro enumerates the capture groups in a regular expression
using an index that is incremented as well as read within a single
expression triggering the Clippy lint eval_order_dependency [1] in
crates using that macro.
[1] https://rust-lang.github.io/rust-clippy/current/index.html#eval_order_dependence

Fix eval_order_dependency Clippy warning triggered by steps! macro

---

src/output/default.rs
tests/cucumber.rs

The `trim_right` method is deprecated as it could be confusing for users
of right-to-left scripts and this replaces its usage by calling `trim_end`
instead which makes the current stable rustc version 1.35 happy.

Replace usage of trim_right by trim_end

---

.travis.yml
Cargo.toml
README.md

Sets up a minimal CI pipeline using publicly available Travis CI service.
The usage of `--no-default-features` can be removed after bbqsrc/cucumber-rust#14 is merged.
`--deny warnings` could be added after bbqsrc/cucumber-rust#16 is merged.

Add Travis CI manifest

---

.travis.yml
src/cli.rs
src/lib.rs
src/output/default.rs
src/panic_trap.rs
tests/cucumber.rs

Since Clippy is often broken on Rust nightly for a while, we allow CI failures for nightly. I also did just suppress Clippy's lints in three places as a "fix" didn't seem helpful.

Make Clippy happy and deny its warnings during CI runs

---

.travis.yml
src/cli.rs
src/lib.rs
src/output/default.rs
src/output/mod.rs
src/panic_trap.rs
tests/cucumber.rs

Also check formatting as part of CI runs to avoid future changes that
would lead to large reformatting again.

Apply the current stable Rustfmt to the whole code base.

---

src/lib.rs

I am not sure if this is intentional as the binding `_before_fns` somewhat looks like it, but if it is not, this also applies before functions in the same way after functions are.

Do not ignore before helper functions.

---

Cargo.toml
build.rs
src/lib.rs
src/output/default.rs
src/output/mod.rs
tests/cucumber.rs

Note that this has no implications for users of this crate as they can continue to use whatever Rust edition they prefer.

Switch to the current Rust edition 2018.

---

src/lib.rs

The explicit lifetime marker inside `RegexTestCase` is not really necessary and hence we can remove it and after that considerably simplify the implementation of `Steps` by removing a lot of explicit lifetime specifications.

Remove explicit lifetime marker from RegexTestCase

---

README.md

A `crate` was added before the `MyWorld` type to compile with `2018` edition of Rust.

Update README.md to 2018 edition

---

src/output/default.rs

When cucumber is processed by an editor, the ANSI escape sequences are
added. This commit  lets the termcolor crate decide  whether to enable
colors based on the environment.

ANSI colors based on term environment

---

src/lib.rs

Example variables  should also be  expanded in the scenario  title and
doc strings. Tables should also  have the variables expanded, which is
not included in this commit.

Replace example variables in docstring and scenario title

---

.gitignore
src/event.rs
src/examples.rs
src/lib.rs
src/output/default.rs
src/runner.rs
tests/cucumber_builder.rs

Added basic support for examples

---

Cargo.toml
features/integration/step_variety.feature
src/event.rs
src/examples.rs
src/lib.rs
tests/integration_test.rs

Presently the `event` and `output` modules are fully private. This prevents users from implementing `EventHandler` because the event types are private.  The lack of access to the `BasicOutput` event handler implementation in the `output` module prevents ends users from building event handlers that both delegate to the standard default handler and their own functionality.
I would like to make an event handler in order to capture failures (and skips, and unimplemented bits) in order to determine the appropriate exit code for my test program. The exit code of the test program is critical for automating detection of test failures across multiple test suites. Ideally, I would like to do this event-based failure capturing with a custom `EventHandler` implementation which also does not have to …

Expose event and output mods in support of user-defined event handling

---

.github/workflows/ci.yml
Cargo.toml
README.md
codegen/Cargo.toml
codegen/features/doctests.feature
codegen/src/attribute.rs
codegen/src/derive.rs
codegen/src/lib.rs
codegen/tests/example.rs
codegen/tests/features/example.feature
codegen/tests/readme.rs
src/lib.rs
src/macros.rs
src/private.rs
src/steps.rs

Closes #81
This PR integrates the machinery described in #81 into `cucumber_rust` crate. This, however, requires to intoduce a `cucumber_rust_codegen` sub-crate.
The initial idea was fully designed and implemented by @ilslv in our closed code base, and I'm just baking his work into this upstream crate. Please, preserve the `Co-authored-by:` for him in commit message on merge.
Filling the CHANGELOG in the correct way was left for maintainers.

Steps auto-wiring and proc macros (#81)

---

src/cucumber.rs
src/event.rs
src/lib.rs
src/output/default.rs
src/runner.rs
tests/integration_test.rs

Currently when running `Cucumber..run()` nothing it reported back to the caller. This changes this behavior by making the result value a `result` with either `()` in the regular case (arguably could be the number of successes or something) and `u64` if any errors have been found. This number also equals the total number of failure found.
To implement this a handy function `failed()` is added to the various events allowing for checking down the tree whether the currently reported item reports a failure or not. All functions have minimal rustdoc documentation added.

Implement failure reporting

---

README.md

Macros rely on the name of the cucumber crate being cucumber_rust

Fix for https://github.com/bbqsrc/cucumber-rust/issues/104

---

CHANGELOG.md
codegen/Cargo.toml
codegen/src/derive.rs
codegen/tests/two_worlds.rs

Resolves #148 
Having multiple `WorldInit` derivers produces multiple structs with same names (`CucumberGiven`, `CucumberWhen`, `CucumberThen`). 
Add struct name at the end to fix error `conflicting implementation for CucumberThen`. 
- Created PR:

Fix multiple `WorldInit` derivers conflicting implementation in single module (#148)

---

CHANGELOG.md
Cargo.toml
book/src/Getting_Started.md
book/tests/Cargo.toml
codegen/CHANGELOG.md
codegen/Cargo.toml
codegen/src/attribute.rs
codegen/src/lib.rs
codegen/tests/example.rs
codegen/tests/features/example.feature
codegen/tests/two_worlds.rs

Allows step implementations to optionally return a Result. This would be a nice-to-have feature, whose main purpose is to allow writing more concise implementations using the `?` operator.

Allow step implementations to return Result

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
README.md
book/src/Features.md
book/tests/Cargo.toml
src/writer/json.rs
src/writer/mod.rs
tests/features/wait/nested/rule.feature
tests/features/wait/outline.feature
tests/features/wait/rule.feature
tests/json.rs
tests/json/correct.json

Resolves #127
For now `cucumber` output can't be parsed by default `CI` tools.
Implement `writer::Json`
- Created PR:

Implement `writer::Json` (#127)

---

CHANGELOG.md
src/writer/mod.rs
src/writer/normalize.rs
src/writer/summarize.rs

Revealed from https://github.com/cucumber-rs/cucumber/issues/177#issuecomment-988606648
Implement `writer::AssertNormalized`
- Created PR:

Implement `writer::AssertNormalized`

---

CHANGELOG.md
src/cli.rs
src/writer/basic.rs
src/writer/out.rs
src/writer/summarize.rs

Resolves #186
For now `writer::Summarize` ignores `Coloring` options. 
Introduce `cli::Colored` trait to propagate `Coloring` to the outer `Writer`s.
- Created PR:

Fix `writer:: Summarize` ignoring `Coloring` options (#186)

---

CHANGELOG.md
Cargo.toml
src/cli.rs
src/cucumber.rs
src/parser/basic.rs
src/parser/mod.rs
src/runner/basic.rs
src/runner/mod.rs
src/writer/basic.rs
src/writer/mod.rs
tests/wait.rs

This pull request is a draft, waiting for the official release of clap v3. However, if needed, It can already be reviewed as the api shouldn't drastically change.
The doc comments on top of structs deriving `clap::Args` or `clap::Parser` is still an issue with Clap v3. So I let the workaround in place.
Closes #155

Replace structopt by clap (#155)

---

CHANGELOG.md
src/runner/basic.rs

For now `Scenario`s are executed in batches, so single long-running `Scenario` can throttle execution.
Make `runner::Basic` execute `Scenario`s as they are available, not in batches.
`cargo test --test wait -- --concurrency=3` time reduced from `~49.5` to `~36.5`.
- Created PR:

Make `runner::Basic` execute `Scenario`s as they are available, not in batches

---

CHANGELOG.md
book/src/cli.md
book/src/quickstart.md
book/src/writing/asserting.md
src/runner/basic.rs

For now there is no way to stop tests execution on first failed `Scenario`.
Add `--fail-fast` CLI option to the `runner::Basic`.
- Created PR:

Add `--fail-fast` CLI option to the `runner::Basic`

---

CHANGELOG.md
src/cucumber.rs
src/writer/fail_on_skipped.rs

Resolve #198 by including `Background` steps into the function that converts `Skipped` steps into `Failed` ones.

Fix `fail_on_skipped` for `Background` steps

---

CHANGELOG.md
Cargo.toml
src/cucumber.rs
src/runner/basic.rs
src/writer/basic.rs
tests/after_hook.rs
tests/json.rs
tests/junit.rs

Resolves #207
For now `after` hook accepts mutable reference to the `World` instance, but only in case `Step` didn't fail.
Accept shared reference to the `World` instance (it's ok because it's not passed on either way) and pass it even in case  `Step` has failed.
- Created PR:

Pass the `World` to after hook even if `Step` has failed (#207)

---

src/runner/basic.rs

For now, failures events of `Step` and `Hook`s are created at the time they are sent, not at the time of their real execution. 
Pass right `event::Metadata`.
- Created PR:

Notify `Writer` with the right `event::Metadata`

---

CHANGELOG.md
book/src/cli.md
codegen/CHANGELOG.md
src/cli.rs
src/parser/basic.rs
src/runner/basic.rs
src/writer/basic.rs
src/writer/junit.rs
tests/cli.rs
tests/features/cli/subcomand_global_option.feature

By declaring CLI options global we allow their usage in subcommands
for the custom CLI.
Issue : #215

Declare CLI options as global

---

book/src/writing/modules.md

Missing dot in URL link to cucumber's anti-patterns fixed

[doc] Missing dot in url

---

CHANGELOG.md
book/src/output/multiple.md
src/cli.rs
src/parser/basic.rs
src/writer/junit.rs

Resolves #231 
Currently `writer::basic::Cli` and `writer::junit::Cli` have argument with conflicting [`Id`](https://docs.rs/clap/latest/clap/struct.Id.html): `verbose`. 
- Use the same name `#[arg(id = "...")` and `#[arg(name = "...")`, as they should be unique due to flattening.
- Document how to deal with actually overlapping CLI arguments.
- Created PR:

Fix conflicting `Id`s of CLI arguments

---

CHANGELOG.md
src/cli.rs
src/cucumber.rs
src/parser/basic.rs
src/runner/basic.rs
src/step.rs
src/writer/basic.rs
src/writer/fail_on_skipped.rs
src/writer/junit.rs
src/writer/libtest.rs
src/writer/normalize.rs
src/writer/out.rs
src/writer/repeat.rs
src/writer/summarize.rs

Not all types implement `Clone`. This could be useful, when we need to run `cucumber` multiple times with slightly changed config for example. 
Add `Clone` implementations to all public types, where possible.
- Created PR:

Add `Clone` implementations to all public types, where possible

---

CHANGELOG.md
Cargo.toml
book/src/cli.md
src/runner/basic.rs
tests/fail_fast.rs
tests/features/fail_fast/no_retry.feature
tests/features/fail_fast/retry.feature
tests/features/fail_fast/retry_delayed.feature

Fixes #241 
https://github.com/cucumber-rs/cucumber/issues/241#issuecomment-1308861572
- Consider `fail_fast` condition when evaluate `is_finished` condition.
- Detect `fail_fast` condition only when there are no retries left.
- Cover `retry` and `fail-fast` conjunction with tests.

Fix hanging with fail-fast option (#241)

---

CHANGELOG.md
Cargo.toml
src/event.rs
src/runner/basic.rs
src/writer/basic.rs
src/writer/fail_on_skipped.rs
src/writer/json.rs
src/writer/libtest.rs
src/writer/summarize.rs
tests/after_hook.rs
tests/features/wait/nested/rule.feature
tests/features/wait/rule.feature
tests/json.rs
tests/json/correct.json
tests/junit.rs
tests/junit/correct.xml
tests/libtest.rs
tests/libtest/correct.stdout
tests/retry_fail_on_skipped.rs
tests/wait.rs

#249
Don't pass info about number of retries, when transforming `Skipped` event into a `Failed`.
- Created PR:

Fix retries with fail on skipped (#249)

---

CHANGELOG.md
src/writer/out.rs

It happens that [`console::Style`](https://docs.rs/console/latest/console/struct.Style.html) uses autodetect for colors.
Force colors on `color=always|never`.
- Created PR:

Fix `color=always|never` CLI options

---

CHANGELOG.md
book/src/SUMMARY.md
book/src/output/index.md
book/src/output/intellij.md
src/writer/libtest.rs
tests/libtest.rs
tests/libtest/correct-report-time.stdout

#264
Support `--report-time` CLI option for `writer::Libtest`.
- Created PR:

Support `--report-time` CLI option for `writer::Libtest` (#264)
